// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6K4oOUzRfe4dHGZj_2hASh3x4j4g10mA',
    appId: '1:525914027982:web:451d77548a1c8a92619d9f',
    messagingSenderId: '525914027982',
    projectId: 'siriparakum-sc',
    authDomain: 'siriparakum-sc.firebaseapp.com',
    storageBucket: 'siriparakum-sc.appspot.com',
    measurementId: 'G-BQMXS5JYKJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhdics9S1tAQ9KEFxe0xeC6YY6k14YM6g',
    appId: '1:525914027982:android:7b555ca41f673322619d9f',
    messagingSenderId: '525914027982',
    projectId: 'siriparakum-sc',
    storageBucket: 'siriparakum-sc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqio3o18Ikw9vLdomfe5ECG8ZUm9r1zQc',
    appId: '1:525914027982:ios:c76365bc7fcc37db619d9f',
    messagingSenderId: '525914027982',
    projectId: 'siriparakum-sc',
    storageBucket: 'siriparakum-sc.appspot.com',
    iosBundleId: 'com.example.siriparakum',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDqio3o18Ikw9vLdomfe5ECG8ZUm9r1zQc',
    appId: '1:525914027982:ios:d453b79d41f89103619d9f',
    messagingSenderId: '525914027982',
    projectId: 'siriparakum-sc',
    storageBucket: 'siriparakum-sc.appspot.com',
    iosBundleId: 'com.example.siriparakum.RunnerTests',
  );
}
